name: build-image

on:
  push:
    paths: 
      - 'agent-image.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Check JSON syntax
      run: jq ./agent_image.json >/dev/null 2>&1 || exit 1
