name: deploy-vmss

on:
  push:
    paths: 
      - 'azuredeploy.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Check JSON syntax
      run: jq . < azuredeploy.json > /dev/null || exit 1

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - run: |
        az group deployment create -g vmss-build-pool --template-file azuredeploy.json --parameters @deploy-parameters.json 
        # now do some testing and delete the scale set
